select 
UPDATE_TIME   
    
    , SITEID
    , FARMID
    , ID_SOURCE
    , SOURCE_NAME
    ,case when CHECKBOX>1 then null else CHECKBOX end as CHECKBOX
    , ORA_20_00
      ,ORA_20_15
, ORA_20_30
      ,ORA_20_45
       ORA_21_00
      ,ORA_21_15
, ORA_21_30
      ,ORA_21_45
  
    from (
select UPDATE_TIME   
    
    , SITEID
    , FARMID
    , ID_SOURCE
    , SOURCE_NAME
    ,  case when CHECKBOX>1 then null else CHECKBOX end as CHECKBOX
    --, 'FORECASTED_POWER' as INDICATOR_NAME
    , MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 0 AND EXTRACT(MINUTE FROM f.datetime) < 15 THEN f.forecasted_power_kw END) AS ORA_20_00,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 15 AND EXTRACT(MINUTE FROM f.datetime) < 30 THEN f.forecasted_power_kw END) AS ORA_20_15,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 30 AND EXTRACT(MINUTE FROM f.datetime) < 45 THEN f.forecasted_power_kw END) AS ORA_20_30,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 45 THEN f.forecasted_power_kw END) AS ORA_20_45,
  
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 0 AND EXTRACT(MINUTE FROM f.datetime) < 15 THEN f.forecasted_power_kw END) AS ORA_21_00,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 15 AND EXTRACT(MINUTE FROM f.datetime) < 30 THEN f.forecasted_power_kw END) AS ORA_21_15,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 30 AND EXTRACT(MINUTE FROM f.datetime) < 45 THEN f.forecasted_power_kw END) AS ORA_21_30,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 45 THEN f.forecasted_power_kw END) AS ORA_21_45
      
      
from integration_schema.FORECAST_SOURCE f
group by 
UPDATE_TIME   
    
    , SITEID
    , FARMID
    , ID_SOURCE
    , SOURCE_NAME
    , CHECKBOX

union all 
select 
    cast (NOW()as TIMESTAMP) as UPDATE_TIME   
    
    , SITEID
    , FARMID
    , '6666' ID_SOURCE
    , 'AVG_SOURCES' SOURCE_NAME
    , '6666' CHECKBOX
    --, 'AVG_SOURCES' as INDICATOR_NAME
    , MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 0 AND EXTRACT(MINUTE FROM f.datetime) < 15 THEN f.AVG_SOURCES END) AS ORA_20_00,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 15 AND EXTRACT(MINUTE FROM f.datetime) < 30 THEN f.AVG_SOURCES END) AS ORA_20_15,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 30 AND EXTRACT(MINUTE FROM f.datetime) < 45 THEN f.AVG_SOURCES END) AS ORA_20_30,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 45 THEN f.AVG_SOURCES END) AS ORA_20_45,
  
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 0 AND EXTRACT(MINUTE FROM f.datetime) < 15 THEN f.AVG_SOURCES END) AS ORA_21_00,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 15 AND EXTRACT(MINUTE FROM f.datetime) < 30 THEN f.AVG_SOURCES END) AS ORA_21_15,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 30 AND EXTRACT(MINUTE FROM f.datetime) < 45 THEN f.AVG_SOURCES END) AS ORA_21_30,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 45 THEN f.AVG_SOURCES END) AS ORA_21_45
      
      
from integration_schema.FORECAST_SOURCE f
group by 
cast (NOW()as TIMESTAMP)  
, SITEID
    , FARMID
    
    , SITEID
    , FARMID
    
union all 
select 
    cast (NOW()as TIMESTAMP) as UPDATE_TIME   
    
    , SITEID
    , FARMID
    , '7777' ID_SOURCE
    , 'AUTO_CORRECTION' SOURCE_NAME
    , '7777' CHECKBOX
--    , 'AUTO_CORRECTION' as INDICATOR_NAME
    , MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 0 AND EXTRACT(MINUTE FROM f.datetime) < 15 THEN f.AUTO_CORRECTION END) AS ORA_20_00,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 15 AND EXTRACT(MINUTE FROM f.datetime) < 30 THEN f.AUTO_CORRECTION END) AS ORA_20_15,
	  MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 30 AND EXTRACT(MINUTE FROM f.datetime) < 45 THEN f.AUTO_CORRECTION END) AS ORA_20_30,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 45 THEN f.AUTO_CORRECTION END) AS ORA_20_45,
  
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 0 AND EXTRACT(MINUTE FROM f.datetime) < 15 THEN f.AUTO_CORRECTION END) AS ORA_21_00,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 15 AND EXTRACT(MINUTE FROM f.datetime) < 30 THEN f.AUTO_CORRECTION END) AS ORA_21_15,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 30 AND EXTRACT(MINUTE FROM f.datetime) < 45 THEN f.AUTO_CORRECTION END) AS ORA_21_30,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 45 THEN f.AUTO_CORRECTION END) AS ORA_21_45
      
      
from integration_schema.FORECAST_SOURCE f
group by 
    cast (NOW()as TIMESTAMP)  
    , SITEID
    , FARMID
    , SITEID
    
union all 
select 
    cast (NOW()as TIMESTAMP) as UPDATE_TIME   
    
    , SITEID
    , FARMID
    , '8888' ID_SOURCE
    , 'MANUAL_CORRECTION' SOURCE_NAME
    , '8888' CHECKBOX
--    , 'MANUAL_CORRECTION' as INDICATOR_NAME
    , MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 0 AND EXTRACT(MINUTE FROM f.datetime) < 15 THEN f.MANUAL_CORRECTION END) AS ORA_20_00,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 15 AND EXTRACT(MINUTE FROM f.datetime) < 30 THEN f.MANUAL_CORRECTION END) AS ORA_20_15,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 30 AND EXTRACT(MINUTE FROM f.datetime) < 45 THEN f.MANUAL_CORRECTION END) AS ORA_20_30,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 20 AND EXTRACT(MINUTE FROM f.datetime) >= 45 THEN f.MANUAL_CORRECTION END) AS ORA_20_45,
  
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 0 AND EXTRACT(MINUTE FROM f.datetime) < 15 THEN f.MANUAL_CORRECTION END) AS ORA_21_00,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 15 AND EXTRACT(MINUTE FROM f.datetime) < 30 THEN f.MANUAL_CORRECTION END) AS ORA_21_15,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 30 AND EXTRACT(MINUTE FROM f.datetime) < 45 THEN f.MANUAL_CORRECTION END) AS ORA_21_30,
      MAX(CASE WHEN EXTRACT(HOUR FROM f.datetime) = 21 AND EXTRACT(MINUTE FROM f.datetime) >= 45 THEN f.MANUAL_CORRECTION END) AS ORA_21_45
	  from integration_schema.FORECAST_SOURCE f
group by 
    cast (NOW()as TIMESTAMP)  
    , SITEID
    , FARMID
    , SITEID
    
)    
order by FARMID, ID_SOURCE